<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAhaviar\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAhaviar/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAhaviar.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAhaviar\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAhaviar\appDevDebugProjectContainer([
    'container.build_hash' => 'Ahaviar',
    'container.build_id' => 'eb380b0e',
    'container.build_time' => 1611856397,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAhaviar');
