<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIibpyqk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIibpyqk/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIibpyqk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIibpyqk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIibpyqk\appProdProjectContainer([
    'container.build_hash' => 'Iibpyqk',
    'container.build_id' => 'df537eec',
    'container.build_time' => 1612017430,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIibpyqk');
